### ISSUE TITLE
Kwikset 910 issues

### ISSUE THREAD

**Issue by stevenascott** [ethayer/lock-manager#47]
Just pulled the latest apps and DH and no love for my 910. Upon installing the main Lock Manager app, and adding the lock, I find this error in the IDE:

> 9d82a715-3555-4d56-b8b8-389fe273fe76  4:55:31 PM: error java.lang.IllegalArgumentException: Command 'updateCodes' is not supported by device 0ef1e9b0-d3b6-4a7e-858a-2b76a7172963 of type 'Z-Wave Lock Reporting'. Supported commands: [poll, lock, unlock, refresh, lock, unlock, setCode, deleteCode, requestCode, reloadAllCodes, unlockWithTimeout, setCodeLength, nameSlot, ping, unlockwtimeout] @ line 545

I've tried several DH and the one that seems to almost work is the ST Z-Wave lock w/codes. Though despite it at least showing the attempt to updateCode, it never gets sent, of course.

![image](https://user-images.githubusercontent.com/15056860/27893803-be12035c-61a3-11e7-86d1-443b06d7eca7.png)

What's interesting, is despite not SETTING the codes, it was able to pull some ancient ones from the lock. Roughly two years old, from previous roommates on another continent. Slot 2 and 3.

![image](https://user-images.githubusercontent.com/15056860/27893856-17ed53c2-61a4-11e7-8bb2-06499819f0e3.png)

**Comment by zachfeldman** [comment]
@ethayer one of my SmartThings apps also depends on this command. I'd be glad to try and troubleshoot together.

**Comment by zachfeldman** [comment]
Latest update from SmartThings (I'm also on the phone with them right now)
https://twitter.com/smartthings/status/883017201019637760

**Comment by zachfeldman** [comment]
The person on the phone said they would send me an updated version of this lock-manager repo with updated code to handle their code change. I don't really know how true that is - it doesn't appear this repo's device handler has been updated in the last 48-72 hours (last update was 25 days ago).

In that case @ethayer , many users of this app may be having an issue? I think you're a volunteer so definitely no pressure but just wanted to alert you to this because it's completely handicapping my integration.

**Comment by zachfeldman** [comment]
@stevenascott @ethayer SmartThings apparently pushed a hotfix a moment ago!
https://community.smartthings.com/t/updatecodes-function-completely-and-erroneously-removed-in-latest-z-wave-lock-reporting-update/92018/2

Things are now working on my end.

**Comment by stevenascott** [comment]
Can confirm. Working great! Thanks everyone.
