### ISSUE TITLE
Unable to install app using current workflow because Samsung Oauth scope to broad

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [ethayer/lock-manager#81]
Not a bug but more a feature request.

I'm a developer at an organization with proprietary code. Following the installation workflow, at one point Samsung requests Oauth access for the Github integration. However, its scope includes the ability to view all my organization's proprietary code, although I want to use lock-manager for my personal home's front door.

<img width="507" alt="screen shot 2018-01-06 at 3 15 47 pm" src="https://user-images.githubusercontent.com/1152361/34644926-8fc72b10-f2f5-11e7-9c78-a8b86d0ed3c4.png">

It would be awesome if there were an installation workflow that didn't require me to grant access to anyone to view private repositories. For now, I won't be able to take advantage of the great work you've done here, because it would violate my company's security policy.

**Comment by tylerjw** [comment]
You can get around this by instead creating smart apps and copying the code into the online editor.  You could also create a second github account with a different email address to use with smartthings.

**Comment by ethayer** [comment]
I had the same qualms when allowing ST access in this way.  It isn't good.  I actually had a few back and forth emails with SmartThings support about it, at I was very angry about an event where a ST employee accidentally pushed code to one of my public repos.

Your issue is not unfounded in logic.

Do what @tylerjw says, and copy the code manually into the SmartThings IDE instead of using the github install method.

Alternativly, shore up your organization's security policy on GitHub.  There are features available that used to be Enterprise only for organizations that have been made global because of issues like this.

## Review Security
https://help.github.com/articles/keeping-your-organization-secure/

Specifically this page: https://help.github.com/articles/reviewing-your-organization-s-installed-integrations/

Your organization should be using a WHITE LIST system for Github integration.  This is really the only way to ensure you or any of your coworkers don't inadvertently expose private repos to a third party.  Best thing is, it's effortless to do and manage.

That as long winded, but I'm with you.  I had the same problem.

**Comment by ethayer** [comment]
I meant to point you to this page here:
https://blog.github.com/2015-01-19-organization-approved-applications/

**Comment by tyrannosaurus-becks** [comment]
Thank you!
